services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\ProductService:
        autowire: true

    App\Controller\FeedbackController:
        arguments:
            $productService: '@App\Service\ProductService'